TAROT_CARDS = [
    {
        "slug": "the-fool",
        "name": "The Fool",
        "keywords": ["beginnings", "curiosity", "leap of faith"],
        "meaning": "新しい流れに飛び込む勇気が、停滞を動かします。",
    },
    {
        "slug": "the-magician",
        "name": "The Magician",
        "keywords": ["willpower", "focus", "manifestation"],
        "meaning": "自分の意思と技術を一点に集めるほど結果が現れます。",
    },
    {
        "slug": "the-high-priestess",
        "name": "The High Priestess",
        "keywords": ["intuition", "inner voice", "mystery"],
        "meaning": "外側の情報より、自分の違和感や直感を優先する局面です。",
    },
    {
        "slug": "the-empress",
        "name": "The Empress",
        "keywords": ["growth", "nurture", "abundance"],
        "meaning": "育てる姿勢が人間関係や仕事の成果を豊かにします。",
    },
    {
        "slug": "the-emperor",
        "name": "The Emperor",
        "keywords": ["structure", "authority", "stability"],
        "meaning": "感情よりもルールと段取りを整えることで前進できます。",
    },
    {
        "slug": "the-hierophant",
        "name": "The Hierophant",
        "keywords": ["tradition", "teaching", "guidance"],
        "meaning": "基本に立ち返り、信頼できる型や助言を取り入れることで道筋が見えます。",
    },
    {
        "slug": "the-lovers",
        "name": "The Lovers",
        "keywords": ["choice", "alignment", "relationship"],
        "meaning": "大切なのは好かれることより、自分の価値観に合う選択です。",
    },
    {
        "slug": "the-chariot",
        "name": "The Chariot",
        "keywords": ["momentum", "discipline", "victory"],
        "meaning": "迷いを減らして一点突破すると、状況を動かせます。",
    },
    {
        "slug": "strength",
        "name": "Strength",
        "keywords": ["patience", "courage", "gentle control"],
        "meaning": "強引さより、粘り強く向き合う姿勢が勝ち筋になります。",
    },
    {
        "slug": "the-hermit",
        "name": "The Hermit",
        "keywords": ["reflection", "solitude", "wisdom"],
        "meaning": "結論を急がず、ひとりで考える時間が精度を上げます。",
    },
    {
        "slug": "wheel-of-fortune",
        "name": "Wheel of Fortune",
        "keywords": ["change", "timing", "turning point"],
        "meaning": "運の波は変わり始めています。流れを読むことが重要です。",
    },
    {
        "slug": "justice",
        "name": "Justice",
        "keywords": ["fairness", "truth", "accountability"],
        "meaning": "感情だけでなく事実と責任の線引きを明確にするほど道が開けます。",
    },
    {
        "slug": "the-hanged-man",
        "name": "The Hanged Man",
        "keywords": ["pause", "surrender", "new perspective"],
        "meaning": "急いで動くより、見方を変えるための停止が状況を好転させます。",
    },
    {
        "slug": "death",
        "name": "Death",
        "keywords": ["ending", "transition", "renewal"],
        "meaning": "終わらせるべき流れを手放すことで、次の始まりに入れます。",
    },
    {
        "slug": "temperance",
        "name": "Temperance",
        "keywords": ["balance", "moderation", "integration"],
        "meaning": "極端に振れず、異なる要素を丁寧に混ぜ合わせる姿勢が鍵です。",
    },
    {
        "slug": "the-devil",
        "name": "The Devil",
        "keywords": ["attachment", "temptation", "shadow"],
        "meaning": "自分を縛っている習慣や執着を自覚すると、主導権を取り戻せます。",
    },
    {
        "slug": "the-tower",
        "name": "The Tower",
        "keywords": ["shock", "collapse", "awakening"],
        "meaning": "無理に保っていた前提が崩れることで、本質に立ち返る機会が来ます。",
    },
    {
        "slug": "the-star",
        "name": "The Star",
        "keywords": ["hope", "healing", "guidance"],
        "meaning": "先を急がず、回復と希望を信じるほど流れは静かに整います。",
    },
    {
        "slug": "the-moon",
        "name": "The Moon",
        "keywords": ["uncertainty", "intuition", "subconscious"],
        "meaning": "見えない不安に飲まれず、曖昧さの中で直感を磨くことが大切です。",
    },
    {
        "slug": "the-sun",
        "name": "The Sun",
        "keywords": ["clarity", "joy", "success"],
        "meaning": "素直さと明るさを前に出すほど、状況は分かりやすく前進します。",
    },
    {
        "slug": "judgement",
        "name": "Judgement",
        "keywords": ["calling", "reflection", "rebirth"],
        "meaning": "過去の流れを見直し、いま本当に応えるべき呼びかけに向き合う時です。",
    },
    {
        "slug": "the-world",
        "name": "The World",
        "keywords": ["completion", "integration", "fulfillment"],
        "meaning": "これまでの積み重ねがまとまり、ひとつの完成へ近づいています。",
    },
]
